### ISSUE TITLE
腾讯微信前端面试经历

### ISSUE THREAD

**Issue by 54017** [54017/blog#4]
## 微信前端工程师实习面试总结

博主在校招季一共投了两次简历，一次内推，一次正式实习生招聘。 内推很遗憾没能通过，正式招聘流程也全部走完了，刚拿到offer，分享一下面试的经验，帮助一下小伙伴
### 内推一面

从投简历到接到邀请面试的邮件大概过了半个月，于是乎就跑去了高大上的TIT创意园，一进去就可以看到各种木质的建筑，充满了小资的气息，沿路的树开着不知名的粉色鲜花，缓解了自己紧张的心情。签到后被带到 B6楼等待面试，话说微信的办公楼特别的奢华，简直不像工作的地方 23333。然后一个很柔嫩高帅的小哥过来了说他是一面面试官，他首先给了我一份笔试题，六道题全是数据结构和算法（哭），博主大概写了45分钟，基本上没写对几题。然后一面小哥没有看手写代码只是问了我一下大概思路（窃喜）然后就开始了面试环节。问的基本是前端常见的问题，如下
1. 各种跨域方法（少见的比如使用 iframe 的 domain）
2. 同源策略
3. OAuth2.0 工作的流程
4. HTML5 / CSS3 的各种新特性

其余的楼主都忘了（逃)，感觉当时自己不在状态，答的比较蛋疼。不过小哥面完后说要让他 leader 来面一下，于是乎高高的 leader 出现了，特别严肃，我立马就萎了。 首先问我为什么不留在 UC移动事业群，博主 blabla 说了之后他点了点头，然后就问我对操作系统，计算机网络感不感兴趣，博主（受到一万点暴击）回答不喜欢操作系统，挺喜欢计网，leader 又问为什么不喜欢操作系统，博主心痛因为不会啊！
于是问了浏览器渲染页面的整个过程，从 DNS, TCP, HTTP 到浏览器解析文件，这里 leader 说答的还不错（毕竟是博主的杀手锏之一啊）。重点来了，leader 去看了我的手写笔试题，很认真的一行行看，然后说这里不对，那里不对，基本就没对的地方。 leader 都没什么想问我问题的兴趣了，于是放了个数据结构大招。 假设腾讯十万员工，有一个索引栏，可以通过点击部门获取属于该部门的所有员工，每个员工有一个工作的邮箱，另外还要提供（前缀／模糊）搜索功能，在输入栏输入员工的首字母拼音就可以将该员工检索出来，要求性能最高，存储压力最小。 博主到现在都不太清楚要怎么做（会做的大牛请告诉我～）
### 内推二面

（居然还有二面），二面在深圳，腾讯大厦果然是奢华大气，一排排的 iMac 闪瞎眼，面试官更加严肃了，问的问题全是我不知道的
1. 怎么防止用户直接发请求到服务端（例如那种刷课软件不停发选课请求到服务器而不是通过用户点击选课按钮）
2. 性能优化 cache-control 相关
3. 一大堆数据结构算法题

持续了一小时，题目真的记不起来了。数据结构没有答出来，心服口服的被刷了
### 校招一面

在大学城雅乐轩酒店面试，进去房间前还想着不要是之前内推的面试官吧，问我同样的问题我肯定还是答不出来，所以墨菲定理？进去后我就觉得啊咧，怎么这么眼熟，面试官发话了“你还记得我吗？”。 我的天原来真的是内推一面时的 leader， 博主简直原地爆炸。当然，也真的问了之前那个部门 - 员工的数据结构题，博主说还是不知道。面试官问这两个多星期来我有没有做些什么东西，博主碰巧做了一个 WebRTC + socket.io + react 的[聊天室](https://github.com/54017/blog/issues/2)，面试官对 WebRTC 还挺感兴趣，于是 blabla 说了一通。最后顺利过关，感谢！
### 校招二面

进去房间前还是想着难道又是深圳那位面试官，忐忑的走进去，感觉并没有见到过，不过面试官说 他们（其他面试官吧？）都说他面过我，可是他没有印象了问我有没有....问了很多前端方面的问题，题主嗯哼答得很棒
1. jQuery 源码
2. 性能优化
3. 浏览器渲染
4. UC 实习的项目

基本上博主准备的四大杀手锏全部使用出来啦，顺理成章的过了（逃）
### HR面

简直都是痛。问了感情经历，最死而无憾的事情，最遗憾的事，腾讯的缺点。 这里博主很作死，说了腾讯实习工资太少，我也不知道我怎么这么傻，可能是因为技术面的后遗症，面试官丢给我一个问题我一定要想出一个答案来，博主一时想不到腾讯的缺点....
### 总结

一定不要让面试官牵着鼻子走，因为面试官不会知道你最拿手的地方在哪里，所以他会问他最了解和感兴趣的地方，你必须要引导面试官进入你的领域，比如你对性能优化有特别深入的了解，那么你一定要把面试官拖在这里听你夸夸其谈，楼主在二面的时候就是强行跑话题把有心得的地方全部讲给面试官听了 23333. 同时你的项目最好包含一些比较新颖的技术，这样容易勾起面试官的兴趣，即使是实验性的个人项目也不要紧的。
对于前端，最好你要看过某些框架的源码并且有一些自己的心得，因为这样会体现你的深入探究的能力，毕竟前端的前期学习曲线太平坦了。
### 杀手锏

整理附上博主的三大面试杀手锏，一般情况下博主可以水很久，三个杀手锏全部用出来，半个小时大概就过去了，面试官基本也会满意。

（面试的时候一定要多多准备一些杀手锏来俘获面试官的心！）
1. <audio> 标签移动端的兼容性问题，当音频包含 cover(封面图片) 等非音频信息时可能导致部分机型（三星mini3）无法下载音频文件（发现这个原因的道路很曲折，博主能水很久，所以面试官觉得还挺出彩）
2. 浏览器渲染的过程，`<link>` 标签为什么要在 `<head>` 里，`<script>` 标签为什么要在底部，当 `<link>`,  `<script>` 同时存在的时候浏览器的行为有什么不同（白屏或者无样式内容闪烁），`<script>` 标签为什么不阻塞后续**资源加载**，为什么脱离文档流做动画还是会卡，但是使用 transform 就不会。这些问题涉及到浏览器渲染的一些知识，需要查阅各种资料和动手做实验后才有深入的了解，建议大家去google，google。
3. jQuery 源码，（基本每个面试官都会问有没有看过哪些框架的源码呀），博主建议阅读 core 模块和 ajax 模块

**Comment by daix6** [comment]
Gossip Girl! :girl:
